bl_user_register:
    pattern: /register
    defaults: { _controller: "BacklogUserBundle:User:register" }
    requirements: { _method: "GET" }

bl_user_registerPost:
    pattern: /register
    defaults: { _controller: "BacklogUserBundle:User:registerPost" }
    requirements: { _method: "POST" }

bl_user_registerSuccess:
    pattern: /register-success
    defaults: { _controller: "BacklogUserBundle:User:registerSuccess" }
    requirements: { _method: "GET" }

bl_session_login:
    pattern: /login
    defaults: { _controller: "BacklogUserBundle:Session:login" }
    requirements: { _method: "GET" }

bl_session_loginCheck:
    pattern: /login-check
    defaults: { _controller: "BacklogUserBundle:Session:loginCheck" }
    requirements: { _method: "POST" }

bl_session_logout:
    pattern: /logout
    defaults: { _controller: "BacklogUserBundle:Session:logout" }
