_backlog:
    resource: "@BacklogBacklogBundle/Resources/config/routing.yml"
_comment:
    resource: "@BacklogCommentBundle/Resources/config/routing.yml"
_user:
    resource: "@BacklogUserBundle/Resources/config/routing.yml"
