security:
    encoders:
        Backlog\AppBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: BacklogAppBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(login|register|register-success)$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: bl_session_loginCheck
                login_path: bl_session_login
            logout:
                path:   bl_session_logout
                target: /
