
# Backlog

bl_backlog_list:
    pattern: /
    defaults: { _controller: "BacklogAppBundle:Backlog:list" }
    requirements: { _method: "GET" }

bl_backlog_show:
    pattern: /b/{uid}
    defaults: { _controller: "BacklogAppBundle:Backlog:show" }
    requirements: { _method: "GET" }

bl_backlog_download:
    pattern: /b/{uid}/download
    defaults: { _controller: "BacklogAppBundle:Backlog:download" }
    requirements: { _method: "GET" }

bl_backlog_new:
    pattern: /backlog/new
    defaults: { _controller: "BacklogAppBundle:Backlog:new" }
    requirements: { _method: "GET" }

bl_backlog_saveNew:
    pattern: /backlogs
    defaults: { _controller: "BacklogAppBundle:Backlog:saveNew" }
    requirements: { _method: "POST" }

bl_backlog_edit:
    pattern: /backlogs/{uid}/edit
    defaults: { _controller: "BacklogAppBundle:Backlog:edit" }
    requirements: { _method: "GET" }

bl_backlog_save:
    pattern: /backlogs/{uid}
    defaults: { _controller: "BacklogAppBundle:Backlog:save" }
    requirements: { _method: "POST" }

# Backlog row

bl_backlogrow_move:
    pattern: /b/{backlog_uid}/{id}/move
    defaults: { _controller: "BacklogAppBundle:BacklogRow:move" }
    requirements: { _method: POST }

bl_backlogrow_show:
    pattern: /b/{backlog_uid}/{id}
    defaults: { _controller: "BacklogAppBundle:BacklogRow:show" }
    requirements: { _method: "GET", id: \d+ }

bl_backlogrow_edit:
    pattern: /b/{backlog_uid}/{id}/edit
    defaults: { _controller: "BacklogAppBundle:BacklogRow:edit" }
    requirements: { _method: "GET", id: \d+ }

bl_backlogrow_new:
    pattern: /b/{backlog_uid}/new
    defaults: { _controller: "BacklogAppBundle:BacklogRow:new" }
    requirements: { _method: "GET" }

bl_backlogrow_save:
    pattern: /b/{backlog_uid}/{id}
    defaults: { _controller: "BacklogAppBundle:BacklogRow:save" }
    requirements: { _method: "POST", id: \d+ }

bl_backlogrow_saveNew:
    pattern: /b/{backlog_uid}
    defaults: { _controller: "BacklogAppBundle:BacklogRow:saveNew" }
    requirements: { _method: "POST", id: \d+ }

bl_backlogrow_finish:
    pattern: /b/{backlog_uid}/{id}/finish
    defaults: { _controller: "BacklogAppBundle:BacklogRow:finish" }
    requirements: { _method: "POST", id: \d+ }

# User

bl_user_register:
    pattern: /register
    defaults: { _controller: "BacklogAppBundle:User:register" }
    requirements: { _method: "GET" }

bl_user_registerPost:
    pattern: /register
    defaults: { _controller: "BacklogAppBundle:User:registerPost" }
    requirements: { _method: "POST" }

bl_user_registerSuccess:
    pattern: /register-success
    defaults: { _controller: "BacklogAppBundle:User:registerSuccess" }
    requirements: { _method: "GET" }

# Security

bl_session_login:
    pattern: /login
    defaults: { _controller: "BacklogAppBundle:Session:login" }
    requirements: { _method: "GET" }

bl_session_loginCheck:
    pattern: /login-check
    defaults: { _controller: "BacklogAppBundle:Session:loginCheck" }
    requirements: { _method: "POST" }

bl_session_logout:
    pattern: /logout
    defaults: { _controller: "BacklogAppBundle:Session:logout" }
