Backlog\UserBundle\Entity\User:
    xml_root_name: user
    exclusion_policy: all
    properties:
        username:
            groups: [backlog_export, user_export]
            expose: true
        initials:
            groups: [user_export]
            expose: true
        fullname:
            groups: [user_export]
            expose: true
        email:
            groups: [user_export]
            expose: true
        backlogs:
            groups: [user_export]
            expose: true
